

386_OBJECTS=\
 $(OBJ_PATH)\$O\waitnopendinginstallevents.obj \





# lowercased
BASEDIR=d:\winddk\7600.16385.1
OBJECT_ROOT=d:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=c:\users\administrator\desktop\git-workspace\win-pvdrivers3.25\waitnopendinginstallevents
OBJ_PATH=c:\users\administrator\desktop\git-workspace\win-pvdrivers3.25\waitnopendinginstallevents
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
